apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    name: myapp-rs
    app: myapp
    type: pod

spec:
  template:
    metadata:
      name: myapp-rs
      labels:
        name: myapp-rs
        app: myapp
        type: front-end

    spec:
      containers:
       - name: hello-world
         image: hello-world


  replicas: 2
  selector:
    matchLabels:
      type: front-end



